# Generated by Django 4.1 on 2022-11-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='student_details',
        ),
    ]
