# Generated by Django 4.1 on 2022-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_details_student_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfirstName', models.CharField(max_length=100)),
                ('tlastName', models.CharField(max_length=100)),
                ('temail', models.CharField(max_length=100)),
                ('tphone', models.CharField(max_length=100)),
                ('tpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
