# Generated by Django 4.1.3 on 2022-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teacher_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='doubts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='teacher_details',
            old_name='tfirstName',
            new_name='tfirstname',
        ),
        migrations.RenameField(
            model_name='teacher_details',
            old_name='tlastName',
            new_name='tlastname',
        ),
    ]
